orgadmin/appmain/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.decorators import login_required
from .views import MyPasswordChangeView, MyPasswordSetView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler500, handler404
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('admin/', admin.site.urls),
    # Dashboard
    path('',include('dashboards.urls')),
    # Apps
    path('apps/',include('apps.urls')),
    # Layouts
    path('layouts/',include('layouts.urls')),
    # Components
    path('components/',include('components.urls')),
    # Pages
    path('pages/',include('pages.urls')),
    # Subscriber
    path('subscribers/',include('subscribers.urls')),
    # taekwondogym
    path('taekwondogym/',include('taekwondogym.urls')),

    path(
        "account/password/change/",
        login_required(MyPasswordChangeView.as_view()),
        name="account_change_password",
    ),
    path(
        "account/password/set/",
        login_required(MyPasswordSetView.as_view()),
        name="account_set_password",
    ),
    # All Auth 
    path('account/', include('allauth.urls')),
    
    #Social Auth
    path('social-auth/',include('social_django.urls',namespace="social")),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


handler404 = 'pages.views.custom_404'
handler500 = 'pages.views.custom_500'

orgadmin/apps/urls.py
from django.urls import path
from apps.views import(
    apps_calendar_view,
    apps_chat_view,
    apps_mailbox_view,
    apps_basicaction_view,
    apps_invoiceaction_view,
    apps_ecommerce_products_view,
    apps_ecommerce_product_details_view,
    apps_ecommerce_add_product_view,
    apps_ecommerce_orders_view,
    apps_ecommerce_update_orders_view,
    apps_ecommerce_delete_orders_view,
    apps_ecommerce_order_details_view,
    apps_ecommerce_customers_view,
    apps_ecommerce_update_customers_view,
    apps_ecommerce_delete_customers_view,
    apps_ecommerce_cart_view,
    apps_ecommerce_checkout_view,
    apps_ecommerce_sellers_view,
    apps_ecommerce_seller_details_view,
    apps_projects_list_view,
    apps_projects_overview_view,
    apps_projects_create_view,
    apps_tasks_kanban_view,
    apps_tasks_list_view,
    apps_tasks_details_view,
    apps_crm_contacts_view,
    apps_crm_add_contacts_view,
    apps_crm_update_contacts_view,
    apps_crm_delete_contacts_view,
    apps_crm_companies_view,
    apps_crm_add_companies_view,
    apps_crm_update_companies_view,
    apps_crm_delete_companies_view,
    apps_crm_deals_view,
    apps_crm_leads_view,
    apps_crm_update_leads_view,
    apps_crm_delete_leads_view,
    apps_crypto_transactions_view,
    apps_crypto_buy_sell_view,
    apps_crypto_orders_view,
    apps_crypto_wallet_view,
    apps_crypto_ico_view,
    apps_crypto_kyc_view,
    apps_invoices_list_view,
    apps_invoices_details_view,
    apps_invoices_create_view,
    apps_tickets_list_view,
    apps_tickets_list_update_view,
    apps_tickets_list_delete_view,
    apps_tickets_details_view,
    apps_nft_marketplace_view,
    apps_nft_explore_view,
    apps_nft_liveauction_view,
    apps_nft_itemdetails_view,
    apps_nft_collections_view,
    apps_nft_creators_view,
    apps_nft_ranking_view,
    apps_nft_wallet_view,
    apps_nft_create_view,

    apps_job_application_view,
    apps_job_update_application_view,
    apps_job_delete_application_view,
    apps_job_candidate_grid_view,
    apps_job_candidate_lists_view,
    apps_job_categories_view,
    apps_job_companies_list_view,
    apps_job_details_view,
    apps_job_grid_lists_view,
    apps_job_lists_view,
    apps_job_new_view,
    apps_job_statistics_view,

    apps_file_manager_view,
    apps_todo_view,
    apps_api_key_view,
)
app_name = "apps"

urlpatterns = [
    # Calendar
    path("calendar", view=apps_calendar_view, name="calendar"),
    # Chat
    path("chat", view=apps_chat_view, name="chat"),
    path("mailbox", view=apps_mailbox_view, name="mailbox"),
    path("basicaction", view=apps_basicaction_view, name="basicaction"),
    path("invoiceaction", view=apps_invoiceaction_view, name="invoiceaction"),

    # Ecommerce
    path("ecommerce/products", view=apps_ecommerce_products_view, name="ecommerce.products"),
    path("ecommerce/product-details", view=apps_ecommerce_product_details_view, name="ecommerce.product_details"),
    path("ecommerce/add-product", view=apps_ecommerce_add_product_view, name="ecommerce.add_product"),
    path("ecommerce/orders", view=apps_ecommerce_orders_view, name="ecommerce.orders"),
    path("ecommerce/update-orders/<int:pk>", view=apps_ecommerce_update_orders_view, name="ecommerce.update_orders"),
    path("ecommerce/delete-orders/<int:pk>", view=apps_ecommerce_delete_orders_view, name="ecommerce.delete_orders"),
    path("ecommerce/order-details", view=apps_ecommerce_order_details_view, name="ecommerce.order_details"),
    path("ecommerce/customers", view=apps_ecommerce_customers_view, name="ecommerce.customers"),
    path("ecommerce/update-customers/<int:pk>", view=apps_ecommerce_update_customers_view, name="ecommerce.update_customers"),
    path("ecommerce/delete-customers/<int:pk>", view=apps_ecommerce_delete_customers_view, name="ecommerce.delete_customers"),
    path("ecommerce/cart", view=apps_ecommerce_cart_view, name="ecommerce.cart"),
    path("ecommerce/checkout", view=apps_ecommerce_checkout_view, name="ecommerce.checkout"),
    path("ecommerce/sellers", view=apps_ecommerce_sellers_view, name="ecommerce.sellers"),
    path("ecommerce/seller-details", view=apps_ecommerce_seller_details_view, name="ecommerce.seller_details"),
    # Projects
    path("projects/list", view=apps_projects_list_view, name="projects.list"),
    path("projects/overview", view=apps_projects_overview_view, name="projects.overview"),
    path("projects/create", view=apps_projects_create_view, name="projects.create"),
    # Tasks
    path("tasks/kanban", view=apps_tasks_kanban_view, name="tasks.kanban"),
    path("tasks/list", view=apps_tasks_list_view, name="tasks.list"),
    path("tasks/details", view=apps_tasks_details_view, name="tasks.details"),
    # CRM
    path("crm/contacts/<int:pk>", view=apps_crm_contacts_view, name="crm.contacts_details"),
    path("crm/contacts", view=apps_crm_add_contacts_view, name="crm.contacts"),
    path("crm/update-contacts/<int:pk>", view=apps_crm_update_contacts_view, name="crm.update_contacts"),
    path("crm/delete-contacts/<int:pk>", view=apps_crm_delete_contacts_view, name="crm.delete_contacts"),
    path("crm/companies/<int:pk>", view=apps_crm_companies_view, name="crm.companies_details"),
    path("crm/companies", view=apps_crm_add_companies_view, name="crm.companies"),
    path("crm/update-companies/<int:pk>", view=apps_crm_update_companies_view, name="crm.update_companies"),
    path("crm/delete-companies/<int:pk>", view=apps_crm_delete_companies_view, name="crm.delete_companies"),
    path("crm/deals", view=apps_crm_deals_view, name="crm.deals"),
    path("crm/leads", view=apps_crm_leads_view, name="crm.leads"),
    path("crm/update-leads/<int:pk>", view=apps_crm_update_leads_view, name="crm.update_leads"),
    path("crm/delete-leads/<int:pk>", view=apps_crm_delete_leads_view, name="crm.delete_leads"),
    # Crypto
    path("crypto/transactions", view=apps_crypto_transactions_view, name="crypto.transactions"),
    path("crypto/buy-sell", view=apps_crypto_buy_sell_view, name="crypto.buy_sell"),
    path("crypto/orders", view=apps_crypto_orders_view, name="crypto.orders"),
    path("crypto/wallet", view=apps_crypto_wallet_view, name="crypto.wallet"),
    path("crypto/ico", view=apps_crypto_ico_view, name="crypto.ico"),
    path("crypto/kyc", view=apps_crypto_kyc_view, name="crypto.kyc"),
    # Invoices
    path("invoices/list", view=apps_invoices_list_view, name="invoices.list"),
    path("invoices/details", view=apps_invoices_details_view, name="invoices.details"),
    path("invoices/create", view=apps_invoices_create_view, name="invoices.create"),
    # Support Tickets
    path("support-tickets/list", view=apps_tickets_list_view, name="tickets.list"),
    path("support-tickets/update-list/<int:pk>", view=apps_tickets_list_update_view, name="tickets.update_list"),
    path("support-tickets/delete-list/<int:pk>", view=apps_tickets_list_delete_view, name="tickets.delete_list"),
    path("support-tickets/details", view=apps_tickets_details_view, name="tickets.details"),

    #NFT Pages
    path("nft/marketplace", view=apps_nft_marketplace_view, name="nft.marketplace"),
    path("nft/explore", view=apps_nft_explore_view, name="nft.explore"),
    path("nft/liveauction", view=apps_nft_liveauction_view, name="nft.liveauction"),
    path("nft/itemdetails", view=apps_nft_itemdetails_view, name="nft.itemdetails"),
    path("nft/collections", view=apps_nft_collections_view, name="nft.collections"),
    path("nft/creators", view=apps_nft_creators_view, name="nft.creators"),
    path("nft/ranking", view=apps_nft_ranking_view, name="nft.ranking"),
    path("nft/wallet", view=apps_nft_wallet_view, name="nft.wallet"),
    path("nft/create", view=apps_nft_create_view, name="nft.create"),

    #Job Pages
    path("job/application", view=apps_job_application_view, name="job.application"),
    path("job/update-application/<int:pk>", view=apps_job_update_application_view, name="job.update_application"),
    path("job/delete-application/<int:pk>", view=apps_job_delete_application_view, name="job.delete_application"),
    path("job/candidate-grid", view=apps_job_candidate_grid_view, name="job.candidate_grid"),
    path("job/candidate-lists", view=apps_job_candidate_lists_view, name="job.candidate_lists"),
    path("job/categories", view=apps_job_categories_view, name="job.categories"),
    path("job/companies-lists", view=apps_job_companies_list_view, name="job.companies_lists"),
    path("job/details", view=apps_job_details_view, name="job.details"),
    path("job/grid-lists", view=apps_job_grid_lists_view, name="job.grid_lists"),
    path("job/lists", view=apps_job_lists_view, name="job.lists"),
    path("job/new", view=apps_job_new_view, name="job.new"),
    path("job/statistics", view=apps_job_statistics_view, name="job.statistics"),

    #File Manager
    path("filemanager", view=apps_file_manager_view, name="filemanager"),

    #ToDO
    path("todo", view=apps_todo_view, name="todo"),
    path("api-key", view=apps_api_key_view, name="api_key"),


]

orgadmin/dashboards/urls.py
from django.urls import path
from dashboards.views import (
    dashboard_view,
    dashboard_analytics_view,
    dashboard_crm_view,
    dashboard_crypto_view,
    dashboard_projects_view,
    dashboard_nft_view,
    dashboard_job_view
)

app_name = 'dashboards'

urlpatterns = [
    path('',view =dashboard_view,name="dashboard"),
    path('dashboard-analytics',view =dashboard_analytics_view,name="dashboard_analytics"),
    path('dashboard-crm', view =dashboard_crm_view,name="dashboard_crm"),
    path('dashboard-crypto', view =dashboard_crypto_view,name="dashboard_crypto"),
    path('dashboard-projects', view =dashboard_projects_view,name="dashboard_projects"),
    path('dashboard-nft', view =dashboard_nft_view,name="dashboard_nft"),    
    path('dashboard-job', view =dashboard_job_view,name="dashboard_job"),    
    
]

orgadmin/templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" {% block html %}lang="en" data-layout="horizontal" data-topbar="dark" data-sidebar-size="lg" data-sidebar="light" data-sidebar-image="none" data-preloader="disable"{% endblock html %}>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock title %} | appmain - Admin & Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico'%}">

    {% block css %}
    {% block extra_css %}
    {% endblock extra_css %}

    <!-- Layout config Js -->
    <script src="{% static 'js/layout.js'%}"></script>
    <!-- Bootstrap Css -->
    <link href="{% static 'css/bootstrap.min.css'%}" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="{% static 'css/icons.min.css'%}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="{% static 'css/app.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
    <!-- custom Css-->
    <link href="{% static 'css/custom.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
    {% endblock css %}
</head>

<body>
    <!-- Begin page -->
    <div id="layout-wrapper">
        {% block header %}
        {% include "partials/topbar.html" %}
        {% endblock header %}
        {% block sidebar %}
        {% include "partials/sidebar.html" %}
        {% endblock sidebar %}
        {% block content %}
        {% block pagetitle %}
        {% endblock pagetitle %}
        {% block footer %}
        {% endblock footer %}
        {% endblock content %}
    </div>
    
    {% block extra_content %}        
    {% endblock extra_content %}
        

    {% block javascript %}
    <!-- JAVASCRIPT -->
    <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'libs/simplebar/dist/simplebar.min.js'%}"></script>
    <script src="{% static 'libs/node-waves/dist/waves.min.js'%}"></script>
    <script src="{% static 'libs/feather-icons/dist/feather.min.js'%}"></script>
    <script src="{% static 'js/pages/plugins/lord-icon-2.1.0.js'%}"></script>
    <script src="{% static 'js/plugins.js'%}"></script>

    {% block extra_js %}
    {% endblock extra_js %}

    <!-- App js -->
    <script src="{% static 'js/app.js'%}"></script>
    {% endblock javascript %}

</body>

</html>

orgadmin/templates/partials/footer.html

{% block footer %}
            <footer class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <script>document.write(new Date().getFullYear())</script> © appmain.
                        </div>
                        <div class="col-sm-6">
                            <div class="text-sm-end d-none d-sm-block">
                                Design & Develop by Themesbrand
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
{% endblock footer %}
    

orgadmin/templates/partials/page-title.html
<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="mb-sm-0">{{title}}</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">{{pagetitle}}</a></li>
                    <li class="breadcrumb-item active">{{title}}</li>
                </ol>
            </div>

        </div>
    </div>
</div>
<!-- end page title -->

orgadmin/templates/partials/topbar.html
{% load static %}
{% block header %}
        <header id="page-topbar">
            <div class="layout-width">
                <div class="navbar-header">
                    <div class="d-flex">
                        <!-- LOGO -->
                        <div class="navbar-brand-box horizontal-logo">
                            <a href="{% url 'dashboards:dashboard'%}" class="logo logo-dark">
                                <span class="logo-sm">
                                    <img src="{% static 'images/logo-sm.png'%}" alt="" height="22">
                                </span>
                                <span class="logo-lg">
                                    <img src="{% static 'images/logo-dark.png'%}" alt="" height="17">
                                </span>
                            </a>

                            <a href="{% url 'dashboards:dashboard'%}" class="logo logo-light">
                                <span class="logo-sm">
                                    <img src="{% static 'images/logo-sm.png'%}" alt="" height="22">
                                </span>
                                <span class="logo-lg">
                                    <img src="{% static 'images/logo-light.png'%}" alt="" height="17">
                                </span>
                            </a>
                        </div>

                        <button type="button" class="btn btn-sm px-3 fs-16 header-item vertical-menu-btn topnav-hamburger" id="topnav-hamburger-icon">
                            <span class="hamburger-icon">
                                <span></span>
                                <span></span>
                                <span></span>
                            </span>
                        </button>

                    </div>

                    <div class="d-flex align-items-center">

                        <div class="ms-1 header-item d-none d-sm-flex">
                            <button type="button" class="btn btn-icon btn-topbar btn-ghost-secondary rounded-circle"
                                data-toggle="fullscreen">
                                <i class='bx bx-fullscreen fs-22'></i>
                            </button>
                        </div>

                        <div class="ms-1 header-item d-none d-sm-flex">
                            <button type="button" class="btn btn-icon btn-topbar btn-ghost-secondary rounded-circle light-dark-mode">
                                <i class='bx bx-moon fs-22'></i>
                            </button>
                        </div>


                        <div class="dropdown ms-sm-3 header-item topbar-user">
                            <button type="button" class="btn" id="page-header-user-dropdown" data-bs-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                <span class="d-flex align-items-center">
                                    <img class="rounded-circle header-profile-user" src="{% static 'images/users/avatar-1.jpg'%}"
                                        alt="Header Avatar">
                                    <span class="text-start ms-xl-2">
                                        <span class="d-none d-xl-inline-block ms-1 fw-medium user-name-text">{{user.username}}</span>
                                        <span class="d-none d-xl-block ms-1 fs-12 text-muted user-name-sub-text">Founder</span>
                                    </span>
                                </span>
                            </button>
                            <div class="dropdown-menu dropdown-menu-end">
                                <!-- item-->
                                <h6 class="dropdown-header">Welcome {{user.username}}!</h6>
                                <a class="dropdown-item" href="{% url 'pages:pages.profile' %}"><i
                                        class="mdi mdi-account-circle text-muted fs-16 align-middle me-1"></i> <span
                                        class="align-middle">Profile</span></a>
                                <a class="dropdown-item" href="{% url 'pages:pages.faqs' %}"><i
                                        class="mdi mdi-lifebuoy text-muted fs-16 align-middle me-1"></i> <span
                                        class="align-middle">Help</span></a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'pages:pages.profile_settings' %}"><span
                                        class="badge bg-soft-success text-success mt-1 float-end">New</span><i
                                        class="mdi mdi-cog-outline text-muted fs-16 align-middle me-1"></i> <span
                                        class="align-middle">Settings</span></a>
                                
                                {% if user.is_authenticated %}
                                    {% if user.has_usable_password %}
                                        <a class="dropdown-item" href="{% url 'account_change_password' %}">
                                            <i class="mdi mdi-key text-muted fs-16 align-middle me-1"></i> 
                                            <span class="align-middle" data-key="t-logout">change password</span>
                                        </a>
                                    {% else %}
                                        <a class="dropdown-item" href="{% url 'account_set_password' %}">
                                            <i class="mdi mdi-key text-muted fs-16 align-middle me-1"></i> 
                                            <span class="align-middle" data-key="t-logout">set password</span>
                                        </a>
                                    {% endif %}
                                        <a class="dropdown-item" href="{% url 'account_logout' %}">
                                            <i class="mdi mdi-logout text-muted fs-16 align-middle me-1"></i> 
                                            <span class="align-middle" data-key="t-logout">Logout</span>
                                        </a>
                                {% endif %}
                            </div>
                        </div>
                        {% if messages %}
                        {% for message in messages %}
                        <input type="hidden" id="login-msg" value="{{message}}">
    
                        <button type="button" class="btn btn-primary" id="liveToastBtn" hidden></button>
                        <div class="position-fixed top-0 end-0 p-3" style="z-index: 11">
                            <div class="toast align-items-right text-white bg-primary border-0" id="toast-message" role="alert"
                                aria-live="assertive" aria-atomic="true">
                                <div class="d-flex">
                                    <div class="toast-body">
                                        {{message}}
                                    </div>
                                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"
                                        aria-label="Close"></button>
                                </div>
                            </div>
                        </div>
    
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </header>
        <!-- removeNotificationModal -->
        <div id="removeNotificationModal" class="modal fade zoomIn" tabindex="-1" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" id="NotificationModalbtn-close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="mt-2 text-center">
                            <lord-icon src="https://cdn.lordicon.com/gsqxdxog.json" trigger="loop" colors="primary:#f7b84b,secondary:#f06548" style="width:100px;height:100px"></lord-icon>
                            <div class="mt-4 pt-2 fs-15 mx-4 mx-sm-5">
                                <h4>Are you sure ?</h4>
                                <p class="text-muted mx-4 mb-0">Are you sure you want to remove this Notification ?</p>
                            </div>
                        </div>
                        <div class="d-flex gap-2 justify-content-center mt-4 mb-2">
                            <button type="button" class="btn w-sm btn-light" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn w-sm btn-danger" id="delete-notification">Yes, Delete It!</button>
                        </div>
                    </div>

                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
{% endblock header %}